<?php

return [
    [
        "id" => 1,
        "slug" => "dr-john-doe",
        "cv" => "https://example.com/cv/john_doe.pdf",
        "photograph" => "https://example.com/photos/john_doe.jpg",
        "phone" => "+39 333 123 4567",
        "email" => "john.doe@example.com",
        "address" => "Via Roma 10, Roma",
    ],
    [
        "id" => 2,
        "slug" => "dr-jane-smith",
        "cv" => "https://example.com/cv/jane_smith.pdf",
        "photograph" => "https://example.com/photos/jane_smith.jpg",
        "phone" => "+39 333 987 6543",
        "email" => "jane.smith@example.com",
        "address" => "Via Milano 25, Milano",
    ],
    [
        "id" => 3,
        "slug" => "dr-maria-rossi",
        "cv" => "https://example.com/cv/maria_rossi.pdf",
        "photograph" => "https://example.com/photos/maria_rossi.jpg",
        "phone" => "+39 333 555 1234",
        "email" => "maria.rossi@example.com",
        "address" => "Via Napoli 30, Napoli"
    ],
    [
        "id" => 4,
        "slug" => "dr-luca-bianchi",
        "cv" => "https://example.com/cv/luca_bianchi.pdf",
        "photograph" => "https://example.com/photos/luca_bianchi.jpg",
        "phone" => "+39 333 789 1234",
        "email" => "luca.bianchi@example.com",
        "address" => "Via Torino 40, Torino",
    ],
    [
        "id" => 5,
        "slug" => "dr-sara-verdi",
        "cv" => "https://example.com/cv/sara_verdi.pdf",
        "photograph" => "https://example.com/photos/sara_verdi.jpg",
        "phone" => "+39 333 222 4444",
        "email" => "sara.verdi@example.com",
        "address" => "Via Firenze 50, Firenze",
    ],
    [
        "id" => 6,
        "slug" => "dr-giovanni-nero",
        "cv" => "https://example.com/cv/giovanni_nero.pdf",
        "photograph" => "https://example.com/photos/giovanni_nero.jpg",
        "phone" => "+39 333 666 7777",
        "email" => "giovanni.nero@example.com",
        "address" => "Via Bologna 60, Bologna",
    ],
    [
        "id" => 7,
        "slug" => "dr-laura-pierce",
        "cv" => "https://example.com/cv/laura_pierce.pdf",
        "photograph" => "https://example.com/photos/laura_pierce.jpg",
        "phone" => "+39 333 444 5555",
        "email" => "laura.pierce@example.com",
        "address" => "Via Venezia 12, Venezia",
    ],
    [
        "id" => 8,
        "slug" => "dr-michael-adams",
        "cv" => "https://example.com/cv/michael_adams.pdf",
        "photograph" => "https://example.com/photos/michael_adams.jpg",
        "phone" => "+39 333 333 2222",
        "email" => "michael.adams@example.com",
        "address" => "Via Verona 20, Verona",
    ],
    [
        "id" => 9,
        "slug" => "dr-anna-moretti",
        "cv" => "https://example.com/cv/anna_moretti.pdf",
        "photograph" => "https://example.com/photos/anna_moretti.jpg",
        "phone" => "+39 333 999 8888",
        "email" => "anna.moretti@example.com",
        "address" => "Via Trieste 15, Trieste",
    ],
    [
        "id" => 10,
        "slug" => "dr-pietro-ferrara",
        "cv" => "https://example.com/cv/pietro_ferrara.pdf",
        "photograph" => "https://example.com/photos/pietro_ferrara.jpg",
        "phone" => "+39 333 111 2222",
        "email" => "pietro.ferrara@example.com",
        "address" => "Via Palermo 18, Palermo",
    ],
    [
        "id" => 11,
        "slug" => "dr-clara-monti",
        "cv" => "https://example.com/cv/clara_monti.pdf",
        "photograph" => "https://example.com/photos/clara_monti.jpg",
        "phone" => "+39 333 444 1234",
        "email" => "clara.monti@example.com",
        "address" => "Via Bari 22, Bari",
    ],
    [
        "id" => 12,
        "slug" => "dr-lorenzo-gallo",
        "cv" => "https://example.com/cv/lorenzo_gallo.pdf",
        "photograph" => "https://example.com/photos/lorenzo_gallo.jpg",
        "phone" => "+39 333 555 6666",
        "email" => "lorenzo.gallo@example.com",
        "address" => "Via Genova 9, Genova",
    ],
    [
        "id" => 13,
        "slug" => "dr-valentina-ricci",
        "cv" => "https://example.com/cv/valentina_ricci.pdf",
        "photograph" => "https://example.com/photos/valentina_ricci.jpg",
        "phone" => "+39 333 888 9999",
        "email" => "valentina.ricci@example.com",
        "address" => "Via Perugia 14, Perugia",
    ],
    [
        "id" => 14,
        "slug" => "dr-giorgio-damiani",
        "cv" => "https://example.com/cv/giorgio_damiani.pdf",
        "photograph" => "https://example.com/photos/giorgio_damiani.jpg",
        "phone" => "+39 333 777 6666",
        "email" => "giorgio.damiani@example.com",
        "address" => "Via L'Aquila 28, L'Aquila",
    ],
    [
        "id" => 15,
        "slug" => "dr-carla-novelli",
        "cv" => "https://example.com/cv/carla_novelli.pdf",
        "photograph" => "https://example.com/photos/carla_novelli.jpg",
        "phone" => "+39 333 444 9999",
        "email" => "carla.novelli@example.com",
        "address" => "Via Reggio 11, Reggio Calabria",
    ],
    [
        "id" => 16,
        "slug" => "dr-alessandro-di-marco",
        "cv" => "https://example.com/cv/alessandro_di_marco.pdf",
        "photograph" => "https://example.com/photos/alessandro_di_marco.jpg",
        "phone" => "+39 333 666 5555",
        "email" => "alessandro.dimarco@example.com",
        "address" => "Via Matera 16, Matera",
    ],
    [
        "id" => 17,
        "slug" => "dr-giulia-fontana",
        "cv" => "https://example.com/cv/giulia_fontana.pdf",
        "photograph" => "https://example.com/photos/giulia_fontana.jpg",
        "phone" => "+39 333 444 2222",
        "email" => "giulia.fontana@example.com",
        "address" => "Via Potenza 5, Potenza",
    ],
    [
        "id" => 18,
        "slug" => "dr-davide-mancini",
        "cv" => "https://example.com/cv/davide_mancini.pdf",
        "photograph" => "https://example.com/photos/davide_mancini.jpg",
        "phone" => "+39 333 333 7777",
        "email" => "davide.mancini@example.com",
        "address" => "Via Caserta 25, Caserta",
    ],
    [
        "id" => 19,
        "slug" => "dr-beatrice-rossini",
        "cv" => "https://example.com/cv/beatrice_rossini.pdf",
        "photograph" => "https://example.com/photos/beatrice_rossini.jpg",
        "phone" => "+39 333 222 3333",
        "email" => "beatrice.rossini@example.com",
        "address" => "Via Modena 13, Modena",
    ],
    [
        "id" => 20,
        "slug" => "dr-alberto-greco",
        "cv" => "https://example.com/cv/alberto_greco.pdf",
        "photograph" => "https://example.com/photos/alberto_greco.jpg",
        "phone" => "+39 333 111 9999",
        "email" => "alberto.greco@example.com",
        "address" => "Via Livorno 7, Livorno",
    ],
    [
        "id" => 21,
        "slug" => "dr-chiara-barone",
        "cv" => "https://example.com/cv/chiara_barone.pdf",
        "photograph" => "https://example.com/photos/chiara_barone.jpg",
        "phone" => "+39 333 888 4444",
        "email" => "chiara.barone@example.com",
        "address" => "Via Ferrara 19, Ferrara",
    ],
];
